### ISSUE TITLE
Update view of selected glyph

### ISSUE THREAD

**Issue by cjdunn** [typemytype/GlyphConstruction#29]
I just found this preview in the corner, it's very nice! Possible bug: it doesn't update live. 

As a user I'm trying to match an existing accented glyph. I see the preview in the main window update as I move anchors around, which is great. But the overlay preview in the corner doesn't update until I click another glyph and then click back. I would expect that these would both update live.

![preview_not_updating](https://user-images.githubusercontent.com/3900241/55902383-5ecb0c80-5b99-11e9-825e-024f4666ab60.png)

(I realized I'm not able to re-open old issues, so I'm making a new issue instead of commenting here: 
_Originally posted by @cjdunn in https://github.com/typemytype/GlyphConstruction/issues/9#issuecomment-481800175_ )

**Comment by typemytype** [comment]
This should be solved along the way..

could you test and close if resolved?

thanks

**Comment by cjdunn** [comment]
@typemytype I just tried this again on the latest version of the extension. The overlay preview still doesn't update live as I move anchors around in the glyph window. Only the main preview updates live. For the overlay preview to update I need to click on the glyph again, even if I already just clicked on it before moving the anchor. I would expect that both the main preview and the overlay preview update at the same time when I move anchors around. Please let me know if you need any more info. 

Also, if you're able to implement the "Show Only Changed Glyphs" option:
https://github.com/typemytype/GlyphConstruction/issues/46

then I can just nudge the anchor around until the glyph disappears from the preview, letting me know that it's aligned correctly ; )  🙏
